spring.profiles.include:
  - include1-from-development
  - include2-from-development
spring:
  datasource:
    username: root
    password: mysql
    url: jdbc:log4jdbc:mysql://localhost:3306/kasakaidDB
#spring.datasource.url=jdbc:mysql://localhost:3306/kasakaidDB
# この設定はNG・ドライバーありませんとエラーがでる。
# spring.datasource.driverClassName = net.sf.log4jdbc.sql.jdbcapi.DriverSpy
# こっちの設定が正しい。
    driver-class-name: net.sf.log4jdbc.DriverSpy
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
# Hibernate 5 implicit naming strategy fully qualified name.
# spring.jpa.hibernate.naming.implicit-strategy=
# Hibernate 5 physical naming strategy fully qualified name.
# spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
duplicate.key: "I'm a development"