delete from TestTable where userId in (1,2);
delete from TestChildTable;
insert into TestTable values (1, 'kasakaid');
insert into TestChildTable values (1, 1, 'yuyamamo');
insert into TestChildTable values (1, 2, 'yuyamamo');
insert into TestChildTable values (1, 3, 'yuyamamo');
insert into TestTable values (2, 'kenmori');
insert into TestChildTable values (2, 1, 'nofukuyo');
insert into TestChildTable values (2, 2, 'nofukuyo');
insert into TestChildTable values (2, 3, 'nofukuyo');
